### ISSUE TITLE
Instagram aborts the connection

### ISSUE THREAD

**Issue by Ahmad-2213** [vrnobody/cfxhttp#3]
I have realized that domains such as i.instagram.com can not be resolved through proxy(maybe the reason is something else but i found this more related):

proxy/freedom: failed to get IP address for domain i.instagram.com > app/dns: returning nil for domain i.instagram.com
proxy/freedom: failed to get IP address for domain cdn.instagram.com > app/dns: returning nil for domain cdn.instagram.com

To reproduce the issue, please connect to your xhttp link and try to open reels in instagram, after 10-30 seconds , the connection will be closed, however, it still works on other apps such as Telegram , youtube and etc...
( I'm using the latest version of the code)

**Comment by vrnobody** [comment]
Workers have many limitations. This script is suitable for websites browsing only. And I don't use IG. Sorry I don't think I can solve this problem.

**Comment by Ahmad-2213** [comment]
The Issue lied on the Smart Placement of Worker.
I turned it off and the problem gone !
So DO NOT Use Smart Placement as it breaks down the Connection.
