### ISSUE TITLE
可以有一个部署在普通nodejs环境的版本吗？

### ISSUE THREAD

**Issue by c21xdx** [vrnobody/cfxhttp#4]
你好，不想使用cf来部署，可以有一个部署在普通nodejs环境的版本吗？

**Comment by vrnobody** [comment]
wrangle是可以本地运行的。具体步骤大概是：
```bash
npm install
npm run dev
````
或者你查下wrangle的手册，我只是会点皮毛。

**Comment by c21xdx** [comment]
好的，谢谢

**Comment by zzlinwq** [comment]
> 你好，不想使用cf来部署，可以有一个部署在普通nodejs环境的版本吗？
在普通nodejs环境部署成功了吗？如何部署

**Comment by c21xdx** [comment]
> > 你好，不想使用cf来部署，可以有一个部署在普通nodejs环境的版本吗？
> > 在普通nodejs环境部署成功了吗？如何部署

没有，我不会nodejs
